import { useState, useEffect } from 'react';
import { Header } from '@/components/Header';
import { ConfidenceScore } from '@/components/ConfidenceScore';
import { MicroGoalCard } from '@/components/MicroGoalCard';
import { StreakBadge } from '@/components/StreakBadge';
import { EncouragementCard } from '@/components/EncouragementCard';
import ConfidenceTrend from '@/components/ConfidenceTrend';
import { SubjectProgress } from '@/components/SubjectProgress';
import {
  mockMicroGoals,
  mockProgress,
  mockEncouragement,
  mockWeeklyProgress,
  mockSubjects
} from '@/data/mockData';
import { MicroGoal } from '@/types/student';
import { Target, Sparkles } from 'lucide-react';

const Index = () => {
  const [goals, setGoals] = useState<MicroGoal[]>([]);
  const [progress, setProgress] = useState(mockProgress);
  const [encouragement, setEncouragement] = useState(mockEncouragement);
  const [isLoading, setIsLoading] = useState(true);

  // Fetch data from Python Backend
  useEffect(() => {
    const fetchData = async () => {
      try {
        const [goalsRes, confidenceRes, encouragementRes] = await Promise.all([
          fetch('http://localhost:8000/generate-goals'),
          fetch('http://localhost:8000/confidence'),
          fetch('http://localhost:8000/encouragement')
        ]);

        if (goalsRes.ok) {
          const data = await goalsRes.json();
          // Transform strings to MicroGoal objects
          const newGoals: MicroGoal[] = data.goals.map((text: string, index: number) => ({
            id: index.toString(),
            studentId: 'student-1',
            date: new Date().toISOString().split('T')[0],
            goalText: text,
            estimatedTime: 20,
            subject: 'General',
            topic: 'General',
            difficulty: 'medium',
            completed: false,
            reason: 'Generated by AI based on your weak topics'
          }));
          setGoals(newGoals);
        }

        if (confidenceRes.ok) {
          const data = await confidenceRes.json();
          setProgress(prev => ({
            ...prev,
            confidenceScore: data.confidence_score
          }));
        }

        if (encouragementRes.ok) {
          const data = await encouragementRes.json();
          setEncouragement({
            id: 'api-gen',
            message: data.message,
            reason: data.reason || "Keep going!",
            emoji: '✨',
            type: 'comfort'
          });
        }

      } catch (error) {
        console.error("Failed to fetch from backend:", error);
        // Fallback to mock data if backend is down
        setGoals(mockMicroGoals);
      } finally {
        setIsLoading(false);
      }
    };

    fetchData();
  }, []);

  const handleCompleteGoal = (id: string) => {
    setGoals(prev =>
      prev.map(goal =>
        goal.id === id
          ? { ...goal, completed: true, completedAt: new Date() }
          : goal
      )
    );

    // Update progress
    setProgress(prev => ({
      ...prev,
      totalGoalsCompleted: prev.totalGoalsCompleted + 1,
      weeklyGoals: prev.weeklyGoals + 1,
      confidenceScore: Math.min(100, prev.confidenceScore + 2),
    }));
  };

  const completedGoals = goals.filter(g => g.completed).length;
  const totalGoals = goals.length;

  if (isLoading) {
    return <div className="min-h-screen flex items-center justify-center">Loading...</div>;
  }

  return (
    <div className="min-h-screen bg-background">
      <Header />

      <main className="container mx-auto px-4 py-8 max-w-6xl">
        {/* Hero Section */}
        <div className="mb-8 text-center">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-calm-sage-light text-primary text-sm font-medium mb-4">
            <Sparkles className="w-4 h-4" />
            <span>Focus on progress, not perfection</span>
          </div>
          <h2 className="font-display text-3xl md:text-4xl font-bold text-foreground mb-2">
            Today's Gentle Goals
          </h2>
          <p className="text-muted-foreground max-w-xl mx-auto">
            Small steps, big confidence. Complete what feels right — there's no pressure here.
          </p>
        </div>

        {/* Progress Summary */}
        <div className="flex items-center justify-center gap-3 mb-8 flex-wrap">
          <div className="flex items-center gap-2 px-4 py-2 rounded-full bg-card shadow-soft">
            <Target className="w-4 h-4 text-primary" />
            <span className="text-sm font-medium">
              <span className="text-primary">{completedGoals}</span>
              <span className="text-muted-foreground">/{totalGoals} goals today</span>
            </span>
          </div>
          {completedGoals === totalGoals && totalGoals > 0 && (
            <div className="px-4 py-2 rounded-full bg-calm-sage-light text-primary text-sm font-medium animate-fade-up">
              🎉 All done! You're amazing!
            </div>
          )}
        </div>

        <div className="grid lg:grid-cols-12 gap-6">
          {/* Main Content - Goals */}
          <div className="lg:col-span-7 space-y-4">
            {goals.map((goal, index) => (
              <MicroGoalCard
                key={goal.id}
                goal={goal}
                onComplete={handleCompleteGoal}
                index={index}
              />
            ))}
          </div>

          {/* Sidebar */}
          <div className="lg:col-span-5 space-y-6">
            <ConfidenceScore />

            <EncouragementCard />

            <StreakBadge
              days={progress.streakDays}
              totalGoals={progress.totalGoalsCompleted}
            />
          </div>
        </div>

        {/* Bottom Section */}
        <div className="grid md:grid-cols-2 gap-6 mt-8">
          <ConfidenceTrend />
          <SubjectProgress subjects={mockSubjects} />
        </div>

        {/* Footer Message */}
        <div className="mt-12 text-center py-8 border-t border-border/50">
          <p className="text-muted-foreground text-sm">
            Remember: Learning is a journey, not a race. Take breaks when you need them. 🌱
          </p>
        </div>
      </main>
    </div>
  );
};

export default Index;
